### ISSUE TITLE
Plugin Info for Liberty plugin missing in pom.xml

### ISSUE THREAD

**Issue by vikramkhatri** [IBMStockTrader/messaging#1]
[INFO] Building StockTrader - messaging EJB 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for net.wasdev.wlp.starters.ms-builder:config:jar:0.1 is missing, no dependency information available
[WARNING] The POM for net.wasdev.wlp.starters.ms-builder:faulttolerance:jar:0.1 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------

**Comment by jwalcorn** [comment]
Fixed today.
