### ISSUE TITLE
Externalize the URL through kubernetes secret

### ISSUE THREAD

**Issue by vikramkhatri** [IBMStockTrader/messaging#2]
Can you please externalize the host in this URL so that we can customize it though kubectl secret.

https://github.com/IBMStockTrader/messaging/blob/5e01437882790f434a6675b35fb691108859daf3/messaging-ejb/src/main/java/com/ibm/hybrid/cloud/sample/portfolio/MessagingMDB.java#L58

The issue with the URL is that the host name is `notification-service`, which is hard coded and will break if yaml file is changed for defining the service.

The second issue is that if MQ is in a separate namespace then the host must be `notification-service/<namespaceName>/svc/cluster.local`

In my case, this is not working since my MQ is in `default` namespace and this service is in `stock-trader` namespace.

Thanks.

**Comment by jwalcorn** [comment]
I delivered this about a year ago in my umbrella helm chart for Stock Trader, and last month in my umbrella OpenShift operator (that embeds the helm chart).  Sorry I forgot to close out this issue then.

![image](https://user-images.githubusercontent.com/28963246/76245576-83e55680-6212-11ea-980c-d2180996fdf4.png)

![image](https://user-images.githubusercontent.com/28963246/76245799-ed656500-6212-11ea-9230-5fdb92410686.png)
