### ISSUE TITLE
Invalid JWT Builder ID

### ISSUE THREAD

**Issue by Raunak-S** [IBMStockTrader/messaging#6]
Error from Messaging service logs:
`[WARNING ] com.ibm.websphere.security.jwt.InvalidBuilderException: CWWKS6008E: The specified JSON Web Token (JWT) builder ID [myBuilder] is not valid. Verify that a JWT builder with the specified ID is configured.`

Same as the outdated ID issue from Looper service: https://github.com/IBMStockTrader/looper/issues/4.

**Comment by jwalcorn** [comment]
Fixed now.  Thanks
